### ISSUE TITLE
Ye yee ye.

### ISSUE THREAD

**Issue by Yagich** [winston-yallow/ye#1]
Ye!!! Yeeeee, ye yee ye "yeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee" ye.
![image](https://user-images.githubusercontent.com/24468819/141931456-d3dc6626-c80b-4953-af69-16a49a71f3eb.png)
ye

**Comment by winston-yallow** [comment]
ye!

**Comment by winston-yallow** [comment]
Ye yeee
[project/src/messages/Message.tscn](https://github.com/winston-yallow/ye/blob/0574b95f/project/src/messages/Message.tscn)

**Comment by Xananax** [comment]
ye

**Comment by Yagich** [comment]
> ye

ye.

> Ye yeee [project/src/messages/Message.tscn](https://github.com/winston-yallow/ye/blob/0574b95f/project/src/messages/Message.tscn)

ye? ye... ye
